config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "children/:id", to: "children#index", as: :children
  resources :families, except: %i[index destroy]
  resources :people
  resources :phones
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :person, inverse_of: :phones
  accepts_nested_attributes_for :person
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  def index
    @phones = Phone.all.order(:number)
  end

  def show
    @phone = Phone.find(params[:id])
  end

  def edit
    @phone = Phone.find(params[:id])
  end

  def update
    # pp(params)
    @phone = Phone.find(params[:id])
    if @phone.update(phone_params)
      redirect_to phone_path(@phone)
    else
      render :edit
    end
  end

  private

  def phone_params
    params
      .require(:phone)
      .permit(:phone_type,
              :number,
              :id,
              person_attributes: [
                :id,
                :name
              ])
  end
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/phones/_fields.html.erb
<fieldset>
  <li>
    <%= f.label :phone_type, "Type" %>
    <%= f.text_field :phone_type %>
    <%= f.label :number, "Number" %>
    <%= f.text_field :number %>
    <% unless local_assigns[:top_level] %>
      <%= f.hidden_field :_destroy %>
      <%= link_to "Remove", '#', class: "remove_fields" %>
    <% end %>
  </li>
</fieldset>

app/views/phones/_form.html.erb
<%= form_for @phone do |phone_form| %>
  <p>
    <%= render partial: "fields", locals: { f: phone_form, top_level: true } %>
  </p>
  <p>
    <%= phone_form.fields_for :person_attributes, @phone.person do |person_fields| %>
      <%= render partial: "people/fields", locals: { f: person_fields } %>
    <% end %>
  </p>
  <p><%= phone_form.submit %></p>
<% end %>

app/views/phones/_phone.html.erb
<li>
  Type: <%= phone.phone_type %>
  Number: <%= phone.number %>
  <% if local_assigns[:top_level] %>
    <%= link_to "Show", phone_path(phone) %>
    <%= link_to "Edit", edit_phone_path(phone) %>
  <% end %>
</li>

app/views/phones/index.html.erb
<ul>
  <%= render partial: "phone", collection: @phones, locals: { top_level: true } %>
  <li><%= link_to "Add Phone", new_phone_path %></li>
</ul>

app/views/phones/show.html.erb
<p>
  Type: <%= @phone.phone_type %>
  Number: <%= @phone.number %>
</p>