config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "children/:id", to: "children#index", as: :children
  resources :families, except: %i[index destroy]
  resources :people
  resources :phones
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :user, optional: true

  has_many :address_people, inverse_of: :person
  accepts_nested_attributes_for :address_people
  # reject_if: :all_blank
  has_many :addresses, through: :address_people

  has_many :phones, inverse_of: :person
  accepts_nested_attributes_for :phones,
                                allow_destroy: true,
                                reject_if: :all_blank

  has_many :parent_links,
           foreign_key: :child_id,
           class_name: "Relationship",
           dependent: :destroy,
           inverse_of: :child
  has_many :parents, through: :parent_links, class_name: "Person"
  # NOTE: Not needed because the parameters are using the `collection_singular_ids` method.
  # It's not "nested" as it's an array on the Person object.
  # accepts_nested_attributes_for :parents, allow_destroy: true

  has_many :child_links,
           foreign_key: :parent_id,
           class_name: "Relationship",
           dependent: :destroy,
           inverse_of: :parent
  has_many :children, through: :child_links, class_name: "Person"
  # NOTE: Not needed because the parameters are using the `collection_singular_ids` method.
  # It's not "nested" as it's an array on the Person object.
  # However, it looks like it's needed in order for `fields_for` to generate the right thing.
  # Or maybe not, since this isn't a simple has_many association.
  accepts_nested_attributes_for :children, allow_destroy: true

  has_many :connections,
           foreign_key: :person_a_id,
           class_name: "Connection",
           dependent: :destroy,
           inverse_of: :person_a
  has_many :connected_people, through: :connections, source: :person_b, class_name: "Person"
  # NOTE: Not needed because the parameters are using the `collection_singular_ids` method.
  # It's not "nested" as it's an array on the Person object.
  # accepts_nested_attributes_for :connections, allow_destroy: true

  include Dag

  def address_types
    address_people.map(&:address_type).uniq
  end

  def to_json
    pp as_json.merge(addresses: addresses.as_json).merge(phones: phones.as_json)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.includes(:children).find(params[:id])
  end

  def create
    # puts pp(params.as_json)
    # puts pp(person_params.as_json)
    @person = Person.new(person_params)
    if @person.save(person_params)
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  def update
    # puts pp(person_params.as_json)
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to person_path(@person)
    else
      render :edit
    end
  end

  private

  def person_params
    params.require(:person).permit(:name,
                                   :id,
                                   child_ids: [],
                                   connected_person_ids: [],
                                   parent_ids: [],
                                   phones_attributes: [
                                     :id, :phone_type, :number, :_destroy
                                   ])
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_fields.html.erb
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.hidden_field :id %>

app/views/people/_form.html.erb
<%= form_for @person do |person_form| %>
  <p>
    <%= render partial: "fields", locals: { f: person_form } %>
  </p>
  <ul class="phone-numbers">
    <%= person_form.fields_for :phones do |phone_fields| %>
      <%= render partial: "phones/fields",
                 locals: { f: phone_fields } %>
    <% end %>
    <p><%= link_to_add_fields "Add Phone", person_form, :phones %></p>
  </ul>
  <% if @person.new_record? %>
  <p>Save the person to enable setting children and parents.</p>
  <% end %>
  <hr>
  <%= person_form.fields_for :children do |child_form| %>
  text
  <% end %>
  <hr>
  <%= render partial: "children/index", locals: { f: person_form } %>
  <!-- <h3>Children</h3>
  <ul>
    <%= person_form.collection_check_boxes(:child_ids,
      Person.all,
      :id,
      :name) do |box| %>
      <li>
        <%= box.check_box(
                  disabled: @person.and_ancestors.include?(box.object) ||
                              @person.new_record?
                ).concat(box.label) %>
      </li>
    <% end %>
  </ul> -->
  <hr>
  <h3>Parents</h3>
  <ul>
  <%= person_form.collection_check_boxes(:parent_ids,
                                         Person.all,
                                         :id,
                                         :name) do |box| %>
    <li>
      <!-- Some interesting code here. You need the onchange because your want
           the current value from the browser, so it has to come from Javascript.
           The `data` hash is standard Rails UJS, but you have to have set up
           the routing. -->
      <!-- FIXME: This whole approach is wrong, too, because when I refresh the
           other box, I'll overwrite whatever changes the user has made and not
           saved. -->
      <%= box.check_box(disabled: @person.and_descendants.include?(box.object) ||
                          @person.new_record?,
                        onchange: "$(this).data('params', 'checked=' + this.checked * this.checked)",
                        data: {
                          remote: true,
                          url: @person.persisted? ? children_path(@person.id) : "#",
                          method: :get
                          })
             .concat(box.label) %>
    </li>
    <% end %>
  </ul>
  <h3>Connections</h3>
  <%= person_form.collection_check_boxes(:connected_person_ids, Person.all, :id, :name) %>
  <p><%= person_form.submit %></p>
<% end %>

app/views/people/_person.html.erb
<p>
  Name: <%= person.name %>
  <%= link_to "Edit", edit_person_path(person) %>
  <%= link_to "Show", person_path(person) %>
</p>

app/views/people/index.html.erb
<%= render partial: "person", collection: @people %>
<%= link_to "Add Person", new_person_path %>

app/views/people/show.html.erb
<p>
  Name:
  <%= @person.name %>
</p>
<ul class="phone-numbers">
  <%= render partial: "phones/phone", collection: @person.phones %>
  <p><%= link_to "Edit", edit_person_path(@person) %></p>
</ul>